language: node_js
os:
  - windows
  - linux
  
node_js:
  - "8"
  - "6"
  - "10"

services:
  - mongodb

before_script:
  - mongod
  
notifications:
  email:
    on_success: never
    on_failure: always
