language: node_js
os:
  - windows
  - linux
  
node_js:
  - "8"
  - "6"
  - "10"

services:
  - mongodb

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mongod ; fi
  
notifications:
  email:
    on_success: never
    on_failure: always
